# Generated by Django 5.0.2 on 2024-10-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KartKat', '0002_shoppinglistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='quantity',
        ),
    ]
